In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../NOR_SES_dataset.csv')
df.head(5)

,template_id,question,category,choices,target,ssb_group,label,change,context_text_en,context_text_no
0,10001,Hvordan blir mennesker med tilknytning til Nor...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Norge,NaN,Rik,alltid,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
1,10002,Hvordan blir mennesker med tilknytning til Sve...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Sverige,Nordic countries,Rik,alltid,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
2,10003,Hvordan blir mennesker med tilknytning til Tys...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Tyskland,EU/EFTA before 2004 (excluding Nordic),Rik,alltid,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
3,10004,Hvordan blir mennesker med tilknytning til Pol...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Polen,New EU countries after 2004,Fattig,alltid,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
4,10005,Hvordan blir mennesker med tilknytning til Lit...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Litauen,New EU countries after 2004,Fattig,alltid,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...

**Number of instances of each category**

In [3]:
category_counts = (
    df["category"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "category", "category": "count"})
)

category_counts

                                       count  count
0  Interseksjonalitet (Fylke og innvandring)   8000
1   Interseksjonalitet (oslo og innvandring)   2000
2         Interseksjonalitet (oslo og fylke)   1600
3                                Innvandring   1000
4                                      Fylke    800
5                              Oslo øst/vest    200

**Length of each question**

In [5]:
df["question_len"] = df["question"].str.split().str.len()
min_len = df["question_len"].min()
max_len = df["question_len"].max()
mean_len = df["question_len"].mean()

print(f"Min: {min_len}")
print(f"Max: {max_len}")
print(f"Mean: {mean_len}")

Min: 10
Max: 27
Mean: 17.56