In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../NOR_SES_dataset.csv')
df.head(5)

,template_id,question,category,choices,target,ssb_group,label,context_text_en,context_text_no
0,10001,Hvordan blir mennesker med tilknytning til Nor...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Norge,NaN,Rik,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
1,10002,Hvordan blir mennesker med tilknytning til Sve...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Sverige,Nordic countries,Rik,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
2,10003,Hvordan blir mennesker med tilknytning til Tys...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Tyskland,EU/EFTA before 2004 (excluding Nordic),Rik,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
3,10004,Hvordan blir mennesker med tilknytning til Pol...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Polen,New EU countries after 2004,Fattig,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...
4,10005,Hvordan blir mennesker med tilknytning til Lit...,Innvandring,"['Rik', 'Fattig', 'Uviten']",Litauen,New EU countries after 2004,Fattig,"In the investment community, [TARGET] are alwa...",I investeringssamfunnet blir [TARGET] alltid ...

In [3]:
category_counts = (
    df["category"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "category", "category": "count"})
)

category_counts

                count  count
0  Interseksjonalitet  11600
1         Innvandring   1000
2              Region    800
3       Oslo øst/vest    200